networks:
  inception_network:
    driver: bridge
services:
  mariadb:
    container_name: mariadb
    build: srcs/requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./secrets:/run/secrets
    networks:
      - inception_network
    restart: always
  wordpress:
    container_name: wordpress
    build: srcs/requirements/wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
      - ./secrets:/run/secrets
    depends_on:
      - mariadb
    networks:
      - inception_network
    restart: always

  nginx:
    container_name: nginx
    build: srcs/requirements/nginx
    image: nginx
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
      - ./secrets:/run/secrets
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception_network
    restart: always

volumes:
  mariadb_data: #nome do volume
    driver: local #meu host
    driver_opts:
      type: none
      o: bind #é pra bindar com o diretório do host, não pra criar um novo
      device: /home/lraggio/data/mariadb #conecta o volume chamado mariadb_data ao path
  wordpress_data:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/lraggio/data/wordpress
