networks:
  inception_network:
    driver: bridge
services:
  mariadb:
    container_name: mariadb
    build: srcs/requirements/mariadb
    image: mariadb
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: always

  wordpress:
    container_name: wordpress
    build: srcs/requirements/wordpress
    image: wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception_network
    restart: always

  nginx:
    container_name: nginx
    build: srcs/requirements/nginx
    image: nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception_network
    restart: always

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt


volumes:
  mariadb_data: #nome do volume
    driver: local #meu host
    driver_opts:
      type: none
      o: bind #é pra bindar com o diretório do host, não pra criar um novo
      device: /home/lraggio/data/mariadb #conecta o volume chamado mariadb_data ao path

  wordpress_data:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/lraggio/data/wordpress
